apiVersion: v1
kind: Namespace
metadata:
  name: ombi
  labels:
    name: ombi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
  namespace: ombi
  labels:
    app: ombi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      volumes:
        - name: ombi
          persistentVolumeClaim:
            claimName: ombi
      containers:
      - name: ombi
        image: linuxserver/ombi:amd64-latest
        env:
        - name: BASE_URL
          value: /ombi
        ports:
        - containerPort: 3579
        volumeMounts:
          - mountPath: /config
            name: ombi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi
  namespace: ombi
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ombi"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi
  namespace: ombi
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: ombi
  namespace: ombi
spec:
  selector:
    app: ombi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3579

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ombi
  namespace: ombi
spec:
  rules:
  - http:
      paths:
      - path: /ombi
        backend:
          serviceName: ombi
          servicePort: 80
